version: 2.1

workflows:
  test-deploy:
    jobs:
       - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn clean
      - run: 
          name: Run Test
          command: mvn clean install
